export const GET_DATA_REQUEST = 'GET_DATA_REQUEST'
export const GET_DATA_SUCCESS = 'GET_DATA_SUCCESS'
export const GET_DATA_FAIL = 'GET_DATA_FAIL'

export const GET_ALL_DATA_REQUEST = 'GET_ALL_DATA_REQUEST'
export const GET_ALL_DATA_SUCCESS = 'GET_ALL_DATA_SUCCESS'
export const GET_ALL_DATA_FAIL = 'GET_ALL_DATA_FAIL'
export const GET_ALL_DATA_RESET = 'GET_ALL_DATA_RESET'
